package $condition_package;
$import_package
import java.util.*;

/**
 * This class was generated by $generator_name
 *
 * @author $username
 * @version $date
 */
public class $condition_type {

    protected String orderBy;
    protected Integer limit;
    protected int offset;
    protected List<Criteria> criteriaList;

    public $condition_type() {
        criteriaList = new ArrayList<>();
    }

    public $condition_type orderByDesc(Column column) {
        return appendOrderBy(column, true);
    }

    public $condition_type orderByAsc(Column column) {
        return appendOrderBy(column, false);
    }

    public $condition_type appendOrderBy(Column column, boolean desc) {
        String sortType = desc ? "desc" : "asc";
        if (null != orderBy) {
            orderBy = orderBy + ", " + column.getColumnName() + " " + sortType;
        } else {
            orderBy = column.getColumnName() + " " + sortType;
        }
        return this;
    }

    public String getOrderBy() {
        return orderBy;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(int limit) {
        this.limit = limit;
    }

    public int getOffset() {
        return offset;
    }

    public void setOffset(int offset) {
        this.offset = offset;
    }

    public List<Criteria> getCriteriaList() {
        return Collections.unmodifiableList(criteriaList);
    }

    public Criteria createCriteria() {
        if (!criteriaList.isEmpty()) {
            throw new IllegalStateException(
                    "criteria already exists; use or() to create another group");
        }
        Criteria criteria = new Criteria();
        criteriaList.add(criteria);
        return criteria;
    }

    public Criteria or() {
        Criteria criteria = new Criteria();
        or(criteria);
        return criteria;
    }

    public void or(Criteria criteria) {
        if (criteriaList.isEmpty()) {
            throw new IllegalStateException(
                    "no criteria exists; call createCriteria() first");
        }
        criteriaList.add(Objects.requireNonNull(criteria, "criteria is null"));
    }

    public boolean hasCriteria() {
        return criteriaList.stream().anyMatch(criteria -> criteria.isValid());
    }

    public void clear() {
        criteriaList.clear();
        orderBy = null;
        limit = null;
        offset = 0;
    }

    public static class Criteria {

        protected List<Criterion> criteria = new ArrayList<>();

        public boolean isValid() {
            return !criteria.isEmpty();
        }

        public List<Criterion> getCriteria() {
            return Collections.unmodifiableList(criteria);
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new NullPointerException("condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new NullPointerException(property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new NullPointerException("between condition for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

$criteria_method_list
    }

    public static class Criterion {

        private final String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            this.condition = condition;
            this.value = value;
            if (value instanceof Collection) {
                if (((Collection<?>) value).isEmpty()) {
                    throw new IllegalArgumentException("empty values on `" + condition + "`");
                }
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }

    public enum Column {
$column_enum_list
        ;

        private final String columnName;

        Column(String columnName) {
            this.columnName = columnName;
        }

        public String getColumnName() {
            return columnName;
        }

        @Override
        public String toString() {
            return columnName;
        }
    }
}