package $mapper_package;

import $entity_package.$entity_type;
${import_package}import org.apache.ibatis.annotations.Param;

import java.util.*;

/**
 * This class was generated by $generator_name
 *
 * @author $username
 * @version $date
 */$at_annotation
public interface $mapper_type {

    int insert($entity_type entity);

    int insertSelective($entity_type entity);

    int batchInsert(List<$entity_type> entity);

    int insertOnDuplicateKeyUpdate($entity_type entity);

    void batchInsertOnDuplicateKeyUpdate(List<$entity_type> entity);

    int deleteByPrimaryKey($primary_key_declare_list);

    int delete(@Param("condition") $condition_type condition);

    $entity_type selectByPrimaryKey($primary_key_declare_list);

    $entity_type selectByPrimaryKeyWithBLOBs($primary_key_declare_list);

    List<$entity_type> select(@Param("condition") $condition_type condition);

    List<$entity_type> selectWithBLOBs(@Param("condition") $condition_type condition);

    List<Map<String, Object>> selectColumns(@Param("columns") List<$condition_type.Column> columns, @Param("condition") $condition_type condition);

    List<$entity_type> selectAll();

    List<$entity_type> selectAllWithBLOBs();

    long count(@Param("condition") $condition_type condition);

    long countAll();

    int updateByPrimaryKey($entity_type entity);

    int updateByPrimaryKeyWithBLOBs($entity_type entity);

    int updateByPrimaryKeySelective($entity_type entity);

    int update(@Param("entity") $entity_type entity, @Param("condition") $condition_type condition);

    int updateWithBLOBs(@Param("entity") $entity_type entity, @Param("condition") $condition_type condition);

    int updateSelective(@Param("entity") $entity_type entity, @Param("condition") $condition_type condition);
}