package $condition_package;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was generated by $generator_name
 *
 * @author $username
 * @version $date
 * @see <a href="https://github.com/jrrwll">Jerry Will's Github</a>
 */
public class $condition_type {

    protected String orderBy;
    protected int limit;
    protected int offset;
    protected List<Criteria> criteriaList;

    public $condition_type() {
        criteriaList = new ArrayList<Criteria>();
    }

    public $condition_type appendOrderBy(Order order, SortType sortType) {
        if (null != orderBy) {
            orderBy = orderBy + ", " + order.getColumnName() + " " + sortType.getValue();
        } else {
            orderBy = order.getColumnName() + " " + sortType.getValue();
        }
        return this;
    }

    public String getOrderBy() {
        return orderBy;
    }

    public int getLimit() {
        return limit;
    }

    public void setLimit(int limit) {
        this.limit = limit;
    }

    public int getOffset() {
        return offset;
    }

    public void setOffset(int limit) {
        this.offset = offset;
    }

    public List<Criteria> getCriteriaList() {
        return criteriaList;
    }

    public void or(Criteria criteria) {
        criteriaList.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = new Criteria();
        criteriaList.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = new Criteria();
        if (criteriaList.isEmpty()) {
            criteriaList.add(criteria);
        }
        return criteria;
    }

    public void clear() {
        criteriaList.clear();
        orderBy = null;

    }

    public enum Order {
        // /**
        //  * $comment
        //  */
        // $column_all_upper("$column"),
        $column_enmu_list;

        private String columnName;

        Order(String columnName) {
            this.columnName = columnName;
        }

        public String getColumnName() {
            return columnName;
        }

        @Override
        public String toString() {
            return columnName;
        }
    }
}