package $condition_package;

import java.util.ArrayList;
import java.util.List;
$extra_import

/**
 * This class was generated by $generator_name
 *
 * @author $username
 * @version $date
 * @see <a href="https://github.com/jrrwll">Jerry Will's Github</a>
 */
public class $criteria_type {

    protected List<Criterion> criteria = new ArrayList<Criterion>();

    public boolean isValid() {
        return criteria.size() > 0;
    }

    public List<Criterion> getCriteria() {
        return criteria;
    }

    protected void addCriterion(String condition) {
        if (condition == null) {
            throw new NullPointerException("condition cannot be null");
        }
        criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
        if (value == null) {
            throw new NullPointerException("condition cannot be null");
        }
        criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
        if (value1 == null || value2 == null) {
            throw new NullPointerException("between condition for " + property + " cannot be null");
        }
        criteria.add(new Criterion(condition, value1, value2));
    }

    $column_method_list

}
