package $entity_package;

import java.io.Serializable;
$extra_import

/**
 * This class was generated by $generator_name
 *
 * @author $username
 * @version $date
 * @see <a href="https://github.com/jrrwll">Jerry Will's Github</a>
 */
public class $entity_type implements Serializable {

    private static final long serialVersionUID = 1L;

    // /**
    //  *  $comment
    //  */
    // private $type $property;

    $property_declare_list

            // public $type get${property_upper}() {
            //     return $property;
            // }
            //
            // public void set${property}(int $property) {
            //     this.$property = $property;
            // }

            $property_get_set_list

    @Override
    public String toString() {
        StringBuilder s = new StringBuilder();
        s.append(getClass().getSimpleName());
        s.append("@").append(hashCode());
        s.append("[");
        // s.append("$property=").append($property);
        // s.append(", $property=").append($property);
        $append_property_list
        s.append("]");
        return s.toString();
    }
}