package $entity_package;

import java.io.Serializable;
import java.util.*;$import_lombok

/**
 * This class was generated by $generator_name
 *
 * @author $username
 * @version $date
 * @see <a href="https://github.com/jrrwll">Jerry Will's Github</a>
 */$at_lombok
public class $entity_type implements Serializable {

    private static final long serialVersionUID = 1L;

$property_declare_list

    @Override
    public String toString() {
        return getClass().getSimpleName()
                + "@" + hashCode()
                + "["
$append_property_list
                + "]";
    }$property_get_set_list
}