package $entity_package;
$import_package
$import_java_package

/**
 * This class was generated by $generator_name
 *
 * @author $username
 * @version $date
 * @see <a href="https://github.com/jrrwll">Jerry Will's Github</a>
 */$at_annotation
public class $entity_type implements Serializable {

    private static final long serialVersionUID = 1L;

$property_declare_list
$property_get_set_list$to_string
}