package $extends_mapper_package;
$extends_import_package
/**
 * This class was generated by $generator_name
 *
 * @author $username
 * @version $date
 * @see <a href="https://github.com/jrrwll">Jerry Will's Github</a>
 */$extends_at_annotation
public interface $extends_mapper_type extends $mapper_type {
}