package $mapper_package;

import $entity_package.$entity_type;
${import_package}import org.apache.ibatis.annotations.Param;

import java.util.*;

/**
 * This class was generated by $generator_name
 *
 * @author $username
 * @version $date
 * @see <a href="https://github.com/jrrwll">Jerry Will's Github</a>
 */$at_annotation
public interface $mapper_type {

    int insert($entity_type entity);

    int insertSelective($entity_type entity);

    int batchInsert(List<$entity_type> entity);

    int deleteByPrimaryKey($primary_key_declare_list);

    int delete($condition_type condition);

    $entity_type selectByPrimaryKey($primary_key_declare_list);
$select_by_primary_key_with_blobs
    List<$entity_type> select($condition_type condition);
$select_with_blobs
    long count($condition_type condition);

    int updateByPrimaryKey($entity_type entity);

    int updateByPrimaryKeySelective($entity_type entity);

    int update(@Param("entity") $entity_type entity, @Param("condition") $condition_type condition);

    int updateSelective(@Param("entity") $entity_type entity, @Param("condition") $condition_type condition);
}